name: Quality

on: pull_request
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Common Setup
        uses: ./.github/composite-actions/install

      - name: Lint
        run: pnpm lint

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Common Setup
        uses: ./.github/composite-actions/install

      - name: Format
        run: pnpm format
